const CHANGE_TEXT = 'SETTINGS/CHANGE_TEXT';
const CHECK_QRCODE = 'SETTINGS/CHECK_QRCODE';
const CHECK_QRCODE_SUCCESS = 'SETTINGS/CHECK_QRCODE_SUCCESS';
const CHECK_QRCODE_FAILURE = 'SETTINGS/CHECK_QRCODE_FAILURE';
const RESET_STATE = 'SETTINGS/RESET_STATE';

export {
  CHANGE_TEXT,
  CHECK_QRCODE,
  CHECK_QRCODE_SUCCESS,
  CHECK_QRCODE_FAILURE,
  RESET_STATE,
};
